# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 19 * *"

name: make

jobs:
  make:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_cran("seqinr")
          remotes::install_cran("data.table")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("covr")
          remotes::install_cran("lintr")
          remotes::install_github("jtextor/epitope-prediction")
          remotes::install_github("richelbilderbeek/pureseqtmr")
        shell: Rscript {0}

      - name: Install PureseqTM
        run: pureseqtmr::install_pureseqtm()
        shell: Rscript {0}

      - name: Make
        run: make

